### PR TITLE
new: support for custom server_id line terminators (fixes warp-tech/russh#34)

### PR DESCRIPTION
**Pull request by evilsocket**
I tried to keep it as simple as possible.

### CODE REVIEW

**Comment by Eugeny** [comment]
The value used for kex hash generation should exclude the linebreaks.

**Comment by evilsocket** [comment]
ops, my bad, fixing

**Comment by evilsocket** [comment]
this creates a few issues in case of a custom (raw) server_id which includes line breaks ... I could trim them forcefully from the string but I don't like this solution ... this change should only affect send_ssh_id. Maybe it's better to just extend it as:

```rust
    pub fn send_ssh_id(&mut self, id: &[u8], custom_line_breaks: Option<&[u8]>) {
        self.buffer.extend(id);
        match custom_line_breaks {
            Some(bytes) => self.buffer.extend(bytes),
            None => {
                self.buffer.push(b'\r');
                self.buffer.push(b'\n');
            }
        }
    }
```  

And then add those bytes as a configuration (default to None so it falls back to the standard default). 

What do you think?

**Comment by evilsocket** [comment]
sent a new commit fixing the issue

**Comment by Eugeny** [comment]
I've taken it upon myself to clean it up a little bit and merged :v:

**Comment by Eugeny** [comment]
@all-contributors please add @evilsocket for code

**Comment by evilsocket** [comment]
thanks a lot! looking forward to the changes :D

**Comment by Eugeny** [comment]
Should be released on crates.io now

**Comment by evilsocket** [comment]
i was referring to the server_id changes :D

**Pull request closed without merging**
